#!/usr/bin/env bash
# This script displays the content of /etc/passwd in a custom format
# Read /etc/passwd line by line
while IFS=: read -r username _ userid group_id _ _ home_directory shell _; do
    # Constructing the output for each user
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."
    echo "USER ID's place is protected by the passcode $userid, more info about the user here: $shell"
    echo "------------------------"
done < /etc/passwd
