#!/usr/bin/env bash
# Loop to print "Best School" 10 times using while loop
i=1
while [ $i -le 10 ]; do
    if [ $i -eq 9 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((i++))
done
