#!/usr/bin/env bash
# This script stops the "4-to_infinity_and_beyond" process indirectly
# Find the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")
# Check if the process is running
if [ -n "$pid" ]; then
    # Find the parent process ID (PPID)
    ppid=$(ps -o ppid= -p "$pid")
    
    # Now terminate the parent process (which may stop the child process)
    # For this, we can use the `kill` of the parent process's parent (indirect stop)
    # You can also try exiting the terminal session
    echo "Stopping the parent process with PID: $ppid"
    exit
else
    echo "Process '4-to_infinity_and_beyond' not found."
fi
